### ISSUE TITLE
Kibana-reporting my case

### ISSUE THREAD

**Issue by Ricardo040794** [birolemekli/kibana-reporting#1]
I am really thankful that you can help me or try. I don't know exactly where are the problems and what i need to change, but when the main program is running doesn't work, i see there are critical errors in the Mail.py and main.py, the other files seems they are running more or less. My priority is being possible to take screenshot and save in the computer, the dashboard, send for the email is better of course, like i told you, i am just now learning python and i am sorry in advance for my mistakes. 

![ChromeSettings](https://user-images.githubusercontent.com/74370396/99089054-bb3bac80-25c4-11eb-82b8-e60f7cc60749.png)

![KibanaLoginPage](https://user-images.githubusercontent.com/74370396/99089057-bbd44300-25c4-11eb-942e-7c16938645a8.png)

![Mail](https://user-images.githubusercontent.com/74370396/99089061-bc6cd980-25c4-11eb-8aaa-4264a705ea8e.png)

![ScreenShotPage](https://user-images.githubusercontent.com/74370396/99089066-bd057000-25c4-11eb-959b-2f9dbd06f992.png)

![main](https://user-images.githubusercontent.com/74370396/99089063-bc6cd980-25c4-11eb-8698-f556f69cdd8e.png)

This is the result when i run the program, Entering Kibana... during 6/7 seconds and after the message that happen a error

![Result](https://user-images.githubusercontent.com/74370396/99089865-c0e5c200-25c5-11eb-9b03-79ec6b47bab2.png)

**Comment by birolemekli** [comment]
> I am really thankful that you can help me or try. I don't know exactly where are the problems and what i need to change, but when the main program is running doesn't work, i see there are critical errors in the Mail.py and main.py, the other files seems they are running more or less. My priority is being possible to take screenshot and save in the computer, the dashboard, send for the email is better of course, like i told you, i am just now learning python and i am sorry in advance for my mistakes.

Hi Ricardo.

Now I will tell you about the ways I will proceed.

1) Disable the --headless configuration in the ChromeSettings.py file. When you enter this, the browser performs transactions without being seen to you. If you disable this, you will see the browser open. If the browser is not opened, check your driver path information. In this way, you can find your error more easily by following the steps in the browser.
<img width="657" alt="screenshot" src="https://user-images.githubusercontent.com/43793262/99149888-d7f9e200-26a1-11eb-82b2-9fd396e97172.png">

2) Do you use any login tools on Kibana? Disable this section in the KibanaLoginPage.py file if you are not using it. 
<img width="789" alt="screenshot" src="https://user-images.githubusercontent.com/43793262/99149622-4047c400-26a0-11eb-9ced-1c373fc75079.png">
This section was used for controlled login when the Searchguard (https://search-guard.com/) plugin was present.

--> If you have come so far without any problems, other parts should work without errors.
You can get the dashboard url link "Kibana-> dashboard-> share-> permalink-> short url" this way.

**I would also like to point out a mistake**

<img width="829" alt="screenshot" src="https://user-images.githubusercontent.com/43793262/99149835-8c473880-26a1-11eb-95c5-c808621e2d1e.png">

You have given the driver path information here, but it should be  _**self.driver = driver**_

``

In addition, sending mail is the last transaction and does not affect previous transactions. It's okay if you don't want to send it. As a picture, the project file is first saved in the **_screenshots_** directory. Then he takes the picture from here and sends an e-mail. You do not need to adjust your mail settings because you want to register.

<img width="670" alt="screenshot" src="https://user-images.githubusercontent.com/43793262/99149967-65d5cd00-26a2-11eb-971f-ac0dbf0f93c2.png">

**Comment by Ricardo040794** [comment]
Hi Birol EMEKLİ
Really thank you for being fast answering and helping me, i didnt have internet during the weekend in the village. 
It was a big help from you, the browser is open automatically now, i don't use any login tools on Kibana so i deleted that lines from your code. I did all the changes you said, chrome driver is open but the username and password are not being written and there are some problems in screenshot program and maybe login i believe but i don't know where exactly.

![login](https://user-images.githubusercontent.com/74370396/99246635-8fefd200-27fd-11eb-88d3-f452fb2f98d0.png)


![screenshot](https://user-images.githubusercontent.com/74370396/99246739-b6157200-27fd-11eb-95a1-9295895e2492.png)

![error](https://user-images.githubusercontent.com/74370396/99246775-c1689d80-27fd-11eb-9aec-7740e4946f6b.png)


There is one more thing, when i copy the dashboard link like you told me "Kibana-> dashboard-> share-> permalink-> short url"  is not possible to copy, i will put also screenshot showing, i need copy a Snapshot or
Saved object( i copy this) because the other doesn't work, there is error after if i use.

![permalink](https://user-images.githubusercontent.com/74370396/99246834-d9d8b800-27fd-11eb-86ee-6b9a5910d186.png)

About sending to email thank you for explain but it is not necessary, just save the dashboard in computer it is, i deleted the mail file from the program.

Best Regards,
Ricardo Rodrigues

**Comment by Ricardo040794** [comment]
I am working on this, the screenshot is saved in my computer now, but is saving the screenshot of login page in kibana and not the dashboard like i want, i think the problem is in the login file because is not writing my username and password and come into as it should. I change your code in the page of screenshot, sorry, but was necessary try different ways, could you please check if there is nothing wrong with that code, because i dont want nothing make problem with the rest of your code. Thank you.

![newscreenshot](https://user-images.githubusercontent.com/74370396/99261267-60988f80-2814-11eb-827a-3f013b69d1ed.png)

**Comment by Ricardo040794** [comment]
The program is working as i want now, one more time thank you for your previous help.
